# -*- coding: utf-8 -*-
"""
Segundo bloco de casos: completa a suite ate 300.

Mesma estrutura de testcases_300.CASOS. Aqui ficam as perguntas menos
obvias: sindromes de apresentacao atipica, comorbidades, situacoes em que
a resposta errada e perigosa, e os pontos onde os livros discordam entre si.
"""

CASOS_B = [
    # ---- 01 Obstetricia geral ---------------------------------------------
    (1, "exames laboratoriais de rotina no pre-natal", {"SOGIMIG", "FEBRASGO"},
     ["primeiro trimestre", "rotina", "exames"]),
    (1, "imunizacoes recomendadas na gestacao", {"SOGIMIG", "FEBRASGO"},
     ["imunizacao", "vacina", "vacinacao"]),
    (1, "suplementacao de ferro e acido folico no pre-natal", {"SOGIMIG", "FEBRASGO"},
     ["ferro", "acido folico", "suplementacao"]),
    (1, "nutricao e ganho de peso na gestacao", {"SOGIMIG", "FEBRASGO"},
     ["nutricao", "peso", "dieta"]),
    (1, "rastreio de diabetes gestacional", {"SOGIMIG", "FEBRASGO"},
     ["diabetes gestacional", "glicemia", "OGTT"]),
    (1, "imunizacoes na gestacao: quais sao indicadas", {"SOGIMIG", "FEBRASGO"},
     ["imunizacao", "vacina", "vacinacao"]),
    (1, "primeira consulta de pre-natal: o que avaliar", {"SOGIMIG", "FEBRASGO"},
     ["primeira consulta", "pre-natal", "historia"]),
    (1, "trabalho de parto espontaneo vs induzido", {"SOGIMIG"},
     ["trabalho de parto", "induc", "parto"]),
    (1, "assistencia ao parto vaginal normal", {"SOGIMIG"},
     ["parto", "assistencia", "vaginal"]),
    (1, "cesarean section: indicaciones e riscos", {"SOGIMIG", "Williams"},
     ["cesarea", "cesariana", "indicacao"]),
    (1, "puerperio: hemorragia pos-parto", {"SOGIMIG", "FEBRASGO"},
     ["puerperio", "pos-parto", "hemorragia"]),
    (1, "depressao pos-parto", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["depressao pos-parto", "depressao", "puerperio"]),
    (1, "amamentacao:advice e contraindicacoes", {"SOGIMIG", "FEBRASGO"},
     ["amamentacao", "aleitamento", "mama"]),
    (1, "planejamento familiar no pos-parto", {"SOGIMIG", "FEBRASGO"},
     ["planejamento familiar", "contracep", "pos-parto"]),

    # ---- 02 Emergencias obstetricas ---------------------------------------
    (2, "preeclampsia grave: sinais de gravidade", {"SOGIMIG", "FEBRASGO"},
     ["pre-eclampsia", "gravidade", "preeclampsia"]),
    (2, "sindrome de HELLP: criterios diagnosticos", {"SOGIMIG", "FEBRASGO"},
     ["HELLP", "hemolise", "transaminase"]),
    (2, "convulsao eclampsia: tratamento", {"SOGIMIG"},
     ["eclampsia", "convulsao", "sulfato de magnesio"]),
    (2, "descolamento prematuro: diagnostico ultrassonografico", {"SOGIMIG"},
     ["descolamento", "ultrassonografia", "placenta"]),
    (2, "rotura uterina: sinais de suspeita", {"SOGIMIG", "Williams"},
     ["rotura uterina", "rotura", "cesarea"]),
    (2, "hemorragia uterina pos-parto: manejo", {"SOGIMIG"},
     ["hemorragia", "pos-parto", "atonia", "puerperio"]),
    (2, "sepsis materna: reconhecimento precoce", {"SOGIMIG", "FEBRASGO"},
     ["sepse", "sepsis", "materna"]),
    (2, "tromboembolismo venoso na gestacao", {"SOGIMIG", "Williams"},
     ["tromboembol", "TEV", "trombose"]),
    (2, "sofrimento fetal agudo: parto de emergencia", {"SOGIMIG"},
     ["sofrimento fetal", "fetal", "emergencia"]),
    (2, "trauma na gestacao", {"SOGIMIG"},
     ["trauma", "acidente", "gestacao"]),

    # ---- 03 Medicina fetal -------------------------------------------------
    (3, "risco fetal no diabetes gestacional", {"SOGIMIG", "FEBRASGO"},
     ["diabetes gestacional", "fetal", "risco"]),
    (3, "cardiopatia fetal: diagnostico", {"SOGIMIG", "Williams"},
     ["cardiopatia", "fetal", "coracao"]),
    (3, "hydrops fetalis", {"SOGIMIG", "Williams"},
     ["hydrops", "fetal", "anasarca"]),
    (3, "sindrome de.transpose de grandes vasos", {"SOGIMIG", "Williams"},
     ["transposicao", "grandes vasos", "cardiopatia"]),
    (3, "gastrosquise e onfalocele", {"SOGIMIG", "Williams"},
     ["gastrosquise", "onfalocele", "parede abdominal"]),
    (3, "displasia broncopulmonar do prematuro", {"SOGIMIG", "Williams"},
     ["bronco", "pulmonar", "prematuro", "displasia"]),
    (3, "enterocolite necrosante", {"SOGIMIG", "Williams"},
     ["enterocolite", "necrosante", "prematuro"]),
    (3, "retinopatia da prematuridade", {"SOGIMIG", "Williams"},
     ["retinopatia", "prematuro", "olho"]),
    (3, "vertigem e estenose forame oval", {"SOGIMIG", "Williams"},
     ["forame oval", "estenose", "fetal"]),
    (3, "gravidez de risco na idade materna avancada", {"SOGIMIG", "FEBRASGO"},
     ["idade materna", "avancada", "risco"]),
    (3, "doenca trofoblastica gestacional", {"SOGIMIG", "Williams", "FEBRASGO"},
     ["mola", "trofoblast", "gestacional"]),
    (3, "sindrome de placenta accreta", {"SOGIMIG", "Williams"},
     ["accreta", "placenta", "invas"]),

    # ---- 04 Infertilidade --------------------------------------------------
    (4, "infertilidade secundaria", {"Williams", "FEBRASGO"},
     ["infertilidade secundaria", "infertil", "secundaria"]),
    (4, "histerossalpingografia: interpretacao", {"Williams", "FEBRASGO"},
     ["histerossalpingografia", "HSG", "trompa"]),
    (4, "AMH e reserva ovariana", {"Williams", "FEBRASGO"},
     ["AMH", "reserva ovariana", "antimullerian"]),
    (4, "protocolo de inducao da ovulacao com clomifeno", {"Williams", "FEBRASGO"},
     ["clomifeno", "inducao", "ovulacao"]),
    (4, "sindrome de hiperestimulacao ovariana", {"Williams", "FEBRASGO"},
     ["hiperestimulacao", "SHO", "ovario"]),
    (4, "infertilidade por fator masculino", {"Williams", "FEBRASGO"},
     ["masculino", "espermograma", "sperm"]),
    (4, "endometriose como causa de infertilidade", {"Williams", "FEBRASGO"},
     ["endometriose", "infertilidade", "infertil"]),
    (4, "falha de permeabilidade tubal e infertilidade", {"Williams", "FEBRASGO"},
     ["trompa", "infertilidade", "aderencia"]),

    # ---- 05 Endocrinologia -------------------------------------------------
    (5, "virilizacao: abordagem da paciente", {"Williams", "FEBRASGO"},
     ["virilizacao", "masculinizacao", "androgen"]),
    (5, "hiperaldosteronismo primario", {"Williams", "FEBRASGO"},
     ["aldosterona", "hiperaldosteronismo", "adrenal"]),
    (5, "diabetes mellitus tipo 2 na mulher", {"Williams", "FEBRASGO"},
     ["diabetes", "glicemia", "HbA1c"]),
    (5, "hipoglicemia e insulinoma", {"Williams", "FEBRASGO"},
     ["hipoglicemia", "insulinoma", "insulina"]),
    (5, "acanthosis nigricans e resistencia insulínica", {"Williams", "FEBRASGO"},
     ["acanthosis", "nigricans", "insulina"]),
    (5, "sindrome dos ovarios policisticos: tratamento", {"Williams", "FEBRASGO"},
     ["policistic", "SOP", "tratamento"]),
    (5, "tireoide: hipertireoidismo e ciclo", {"Williams", "FEBRASGO"},
     ["hipertireoidismo", "tireoide", "tiroide"]),

    # ---- 06 Menopausa ------------------------------------------------------
    (6, "perimenopausa: fase e sintomas", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["perimenopausa", "climaterio", "sintomas"]),
    (6, "qualidade de vida pos-menopausa", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["qualidade de vida", "menopausa", "sintomas"]),
    (6, "hormonioterapia: vias de administração", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["hormonioterapia", "terapia hormonal", "transdermica"]),
    (6, "sangramento pos-menopausa: investigação", {"Williams", "FEBRASGO"},
     ["sangramento", "menopausa", "pos-menopausa"]),
    (6, "osteoporose: bisfosfonatos", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["bisfosfonato", "osteoporose", "densidade"]),
    (6, "risco de demencia e hormonioterapia", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["demencia", "cognicao", "hormonal"]),
    (6, "insonia e ansiedade no climaterio", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["insonia", "ansiedade", "climaterio"]),

    # ---- 07 Contracepcao ---------------------------------------------------
    (7, "anticoncepcional injetavel mensal", {"SOGIMIG", "FEBRASGO"},
     ["injetavel", "mensal", "anticoncepcional"]),
    (7, "implante|subcutaneo anticoncepcional", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["implante", "subcutaneo", "progestageno"]),
    (7, "anticoncepcional progestageno: quem pode usar", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["progestageno", "mini-pilula", "anticoncepcional"]),
    (7, "DIU: colocacao e contraindicacoes", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["DIU", "dispositivo intrauterino", "cobre"]),
    (7, "contracepcao em paciente com diabetes", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["diabetes", "contracep", "anticoncepcional"]),
    (7, "contracepcao apos o parto: lactacao amenorreica", {"SOGIMIG", "FEBRASGO"},
     ["lactacao", "amamenta", "contracep"]),
    (7, "violencia e contrariaceptive coercion", {"SOGIMIG", "FEBRASGO"},
     ["violencia", "contracepcao", "coercao"]),
    (7, "anticoncepcional e trombose: avaliacao de risco", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["tromboembol", "risco", "anticoncepcional"]),

    # ---- 08 Uroginecologia -------------------------------------------------
    (8, "incontinencia fecal e anal", {"Williams", "FEBRASGO"},
     ["incontinencia", "anal", "fecal"]),
    (8, "disfuncao sexual:Vaginal introito e_owner", {"Williams", "FEBRASGO"},
     ["vaginal", "introito", "dor"]),
    (8, "prolapso de parede vaginal anterior", {"Williams", "FEBRASGO"},
     ["prolapso", "parede anterior", "vaginal"]),
    (8, "cistite intersticial", {"Williams", "FEBRASGO"},
     ["cistite intersticial", "dor", "bexiga"]),
    (8, "incontinencia de esforco: tratamento cirurgico", {"Williams", "FEBRASGO"},
     ["incontinencia", "esforco", "cirurgia", "sling"]),

    # ---- 09 Oncologia ------------------------------------------------------
    (9, "cancer de colo:reeze abordagem colposcopica", {"Williams", "FEBRASGO"},
     ["colposcopia", "colo", "cervical"]),
    (9, "biopsia de linfonodo sentinela no cancer ginecológico", {"Williams"},
     ["sentinela", "linfonodo", "ganglio"]),
    (9, "quimioterapia neoadjuvante", {"Williams"},
     ["neoadjuvante", "quimioterapia", "quimio"]),
    (9, "radoterapia pélvica: indicando", {"Williams"},
     ["radioterapia", "radiacao", "pelvica"]),
    (9, "tumor de mama triplo negativo", {"Williams", "FEBRASGO"},
     ["triplo negativo", "mama", "receptor"]),
    (9, "rastreio de cancer de colon e ovario", {"Williams", "FEBRASGO"},
     ["colon", "ovario", "rastreio"]),

    # ---- 10 Mastologia -----------------------------------------------------
    (10, "c mama: malignidade e imagem", {"Williams"},
     ["mama", "malignidade", "mamografia"]),
    (10, "mastectomia xMxMxMxHug", {"Williams"},
     ["mastectomia", "conservador", "mama"]),
    (10, "quimioterapia adjuvante em mama", {"Williams"},
     ["adjuvante", "quimioterapia", "mama"]),
    (10, "hirsuExame de mama em paciente de alto risco", {"Williams", "FEBRASGO"},
     ["alto risco", "mama", "rastreio"]),

    # ---- 11 Pediatrica e adolescente ---------------------------------------
    (11, "criptorquidismo", {"Williams"}, ["criptorquidismo", "testiculo", "criptorquid"]),
    (11, "hipospadias", {"Williams"}, ["hipospadias", "uretra", "penis"]),
    (11, "vaginite em menina pre-puberal", {"Williams", "FEBRASGO"},
     ["vaginite", "prepuberal", "menina"]),
    (11, "queixas menstruais em adolescente", {"Williams", "FEBRASGO"},
     ["adolescente", "menstrua", "queixa"]),
    (11, "anticoncepcional em adolescente", {"Williams", "FEBRASGO"},
     ["adolescente", "anticoncepcional", "contracep"]),

    # ---- 12 Colposcopia ----------------------------------------------------
    (12, "colposcopia: preparo e contraindicacoes", {"Williams", "FEBRASGO"},
     ["colposcopia", "colposcop", "contraindic"]),
    (12, "lesao cervical: escova, curetagem e biopsia", {"Williams", "FEBRASGO"},
     ["biopsia", "curetagem", "cervical"]),
    (12, "teste de HPV e citologia: estrategia combinada", {"Williams", "FEBRASGO"},
     ["HPV", "citologia", "rastreio"]),
    (12, "verruga genital e imunidade", {"Williams", "FEBRASGO"},
     ["verruga", "condiloma", "imunidade"]),

    # ---- 13 Cirurgia -------------------------------------------------------
    (13, "laparotomia e via de acesso na cesariana", {"Williams", "SOGIMIG"},
     ["cesariana", "laparotomia", "acesso"]),
    (13, "miomectomia histeroscopica", {"Williams", "FEBRASGO"},
     ["miomectomia", "histeroscop", "submucosa"]),
    (13, "anexectomia: indicacao", {"Williams", "FEBRASGO"},
     ["anexectomia", "ovario", "indicacao"]),
    (13, "cirurgia durante a gestacao", {"Williams", "SOGIMIG"},
     ["gestacao", "cirurgia", "intrauterin"]),

    # ---- 14 Endometriose ---------------------------------------------------
    (14, "endometriose superficial e profunda", {"Williams", "FEBRASGO"},
     ["endometriose", "profunda", "superficial"]),
    (14, "excisao de endometrioma por laparoscopia", {"Williams", "FEBRASGO"},
     ["endometrioma", "laparoscop", "excisao"]),
    (14, "endometriose e dor: abordagem", {"Williams", "FEBRASGO"},
     ["endometriose", "dor", "analges"]),

    # ---- 15 Adenomiose -----------------------------------------------------
    (15, "adenomiose: ultrassonografia e ressonancia", {"Williams", "FEBRASGO"},
     ["adenomiose", "ultrassonografia", "ressonancia"]),
    (15, "adenomiose: tratamento medicamentoso", {"Williams", "FEBRASGO"},
     ["adenomiose", "tratamento", "hormonal"]),
    (15, "adenomiose e dor pelvica cronica", {"Williams", "FEBRASGO"},
     ["adenomiose", "dor", "pelvica"]),
    (15, "adenomiose: ablacao endometrial", {"Williams", "FEBRASGO"},
     ["adenomiose", "ablacao", "endometrial"]),
    (15, "adenomiose: impacto na fertilidade", {"Williams", "FEBRASGO"},
     ["adenomiose", "fertilidade", "infertilidade"]),

    # ---- 16 Leiomiomas -----------------------------------------------------
    (16, "mioma submucoso: consequences", {"Williams", "FEBRASGO"},
     ["submucoso", "mioma", "menorragia"]),
    (16, "mioma e dor pelvica", {"Williams", "FEBRASGO"},
     ["mioma", "dor", "pelvica"]),
    (16, "tratamento medicamentoso do mioma", {"Williams", "FEBRASGO"},
     ["mioma", "medicamentoso", "agonista"]),
    (16, "mioma em gestacao", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["mioma", "gestacao", "leiomioma"]),

    # ---- 17 Disturbios menstruais -----------------------------------------
    (17, "amenorreia primária", {"Williams", "FEBRASGO"},
     ["amenorreia primaria", "menarca", "primaria"]),
    (17, "menstruacao e anticoncepcional", {"Williams", "FEBRASGO"},
     ["menstruacao", "anticoncepcional", "ciclo"]),
    (17, "coagulopatia e menorragia", {"Williams", "FEBRASGO"},
     ["coagulopatia", "menorragia", "Von Willebrand"]),
    (17, "sindrome premenstrual: tratamento", {"Williams", "FEBRASGO"},
     ["premenstrual", "tratamento", "SSRI"]),

    # ---- 18 Dor pelvica -----------------------------------------------------
    (18, "dor pélvica: CID no contexto", {"Williams", "FEBRASGO"},
     ["dor pelvica", "CID", "sindrome"]),
    (18, "neuromodulacao para dor pelvica", {"Williams", "FEBRASGO"},
     ["neuromodulacao", "dor", "pelvica"]),
    (18, "exercicio e dor pélvica crônica", {"Williams", "FEBRASGO"},
     ["dor pelvica", "exercicio", "fisioterapia"]),
    (18, "dor pélvica: avaliação ginecológica", {"Williams", "FEBRASGO"},
     ["dor pelvica", "avaliacao", "ginecologica"]),
    (18, "síndrome de dor pélvica: tratamento", {"Williams", "FEBRASGO"},
     ["dor pelvica", "tratamento", "dor"]),

    # ---- 19 Infeccoes ------------------------------------------------------
    (19, "abcesso tubo-ovariano", {"Williams", "FEBRASGO"},
     ["abcesso", "tubo", "ovario", "PID"]),
    (19, "candidíase recorrente", {"Williams", "FEBRASGO"},
     ["candid", "recorrente", "vulva"]),
    (19, "clamidia: tripladziesnie testagem", {"Williams", "FEBRASGO"},
     ["clamidia", "testagem", "rastreio"]),
    (19, "sifilis e gestacao", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["sifilis", "penicilina", "gestacao"]),
    (19, "vaginose: diagn óstico diferencial", {"Williams", "FEBRASGO"},
     ["vaginose", "diferencial", "bacteriana"]),

    # ---- 20 Aborto ---------------------------------------------------------
    (20, "aborto incompleto: conduta", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["incompleto", "aborto", "conduta"]),
    (20, "aborto medicamentoso", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["medicamentoso", "mifepristona", "misoprostol"]),
    (20, "perda gestacional recorrente: protocolo", {"Williams", "FEBRASGO"},
     ["recorrente", "protocolo", "avaliacao"]),
    (20, "causas geneticas de aborto", {"Williams", "FEBRASGO"},
     ["genetic", "cromossom", "aborto"]),

    # ---- 21 Ectopica -------------------------------------------------------
    (21, "ectopica: analise do hCG em disco", {"SOGIMIG", "Williams"},
     ["hCG", "disco", "ectopica"]),
    (21, "ectopica cervical", {"SOGIMIG", "Williams"},
     ["cervical", "ectopica", "canal cervical"]),
    (21, "ectopica e uso de methotrexate", {"SOGIMIG", "Williams"},
     ["metionato", "ectopica", "dose"]),
    (21, "ectopica: acompanhamento apos tratamento", {"SOGIMIG", "Williams"},
     ["acompanhamento", "hCG", "ectopica"]),

    # ---- 22 Hemorragia uterina ---------------------------------------------
    (22, "HUA: protocolo de abordagem", {"Williams", "FEBRASGO"},
     ["HUA", "hemorragia uterina", "sangramento"]),
    (22, "sangramento na gestacao:.guias iniciais", {"SOGIMIG"},
     ["sangramento", "gestacao", "inicial"]),
    (22, "anticoagulante e sangramento uterino", {"Williams", "FEBRASGO"},
     ["anticoagulante", "sangramento", "uterino"]),
    (22, "sangramento uterino: avaliação endometrial", {"Williams", "FEBRASGO"},
     ["sangramento", "endometrial", "endometrio"]),

    # ---- 23 Abdome agudo ---------------------------------------------------
    (23, "torção anexial: pacientes de alto risco", {"Williams", "FEBRASGO"},
     ["torsao", "alto risco", "anexial"]),
    (23, "cisto ovariano complicado", {"Williams", "FEBRASGO"},
     ["cisto", "complicado", "ovario"]),
    (23, "mioma torsionado", {"Williams", "FEBRASGO"},
     ["torsao", "mioma", "leiomioma"]),
    (23, "dor pélvica aguda: abordagem cirúrgica", {"Williams", "FEBRASGO"},
     ["dor pelvica", "aguda", "cirurgica"]),

    # ---- 24 Saude da mulher idosa -----------------------------------------
    (24, "demencia: diagnostico diferencial", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["demencia", "diferencial", "alzheimer"]),
    (24, "fratura por osteoporose: preventing", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["fratura", "osteoporose", "queda"]),
    (24, "medicacao na idosa: polifarmacia", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["polifarmacia", "medicacao", "idosa"]),
    (24, "quedas e funcGQional na terceira idade", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["queda", "funcional", "idosa"]),
]
