# -*- coding: utf-8 -*-
"""
Casus de teste para o Differential Matrix Engine.

Formato de cada caso:
    (modulo, query, livros_aceitos, ancoras)

    modulo         int 1-24 (ver MODULOS)
    query          texto clinico em linguagem natural, como o usuario digita
    livros_aceitos set  de livros que DEVEM conseguir responder
    ancoras        list de variantes; basta UMA aparecer no texto recuperado

Sobre as ancoras: o OCR dos PDFs e ruim ("Aspectos ~ticos", "mterrupcao",
"c_rdio"), entao cada ancora e uma lista de variantes e o teste exige
qualquer uma. O casamento e normalizado (sem acento, minusculo).

As ancoras existem para provar que a base REALMENTE contem o assunto, e nao
apenas que o vetor trouxe alguma coisa qualquer. Um caso so passa se:
  (a) um livro aceito aparece no top-k      -> prova o roteamento
  (b) alguma ancora aparece no texto        -> prova a cobertura do conteudo
Se (b) falha, a base nao tem o assunto: isso e um bug de indexacao, nao do LLM.
"""

CASOS = [
    # ---- 01 Obstetricia geral e pre-natal de baixo risco -------------------
    (1, "conduta no primeiro trimestre de gestacao", {"SOGIMIG", "FEBRASGO"},
     ["primeiro trimestre", "primeiro trimestre", "1o trimestre"]),
    (1, "quantas consultas de pre-natal uma gestacao de risco normal precisa",
     {"SOGIMIG", "FEBRASGO"}, ["consultas de pre-natal", "consultas de prenatal", "pre-natal"]),
    (1, "suplementacao de acido folico e ferro durante a gestacao", {"SOGIMIG", "FEBRASGO"},
     ["acido folico", "ferro", "suplementacao"]),
    (1, "quando fazer a primeira ultrassonografia obstetrica", {"SOGIMIG"},
     ["ultrassonografia", "ultrassom", "primeira ultrassonografia"]),
    (1, "exames de rotina no primeiro trimestre", {"SOGIMIG", "FEBRASGO"},
     ["primeiro trimestre", "exames", "rotina"]),
    (1, "vacina contra gripe e nulo e Collaboration gestante", {"SOGIMIG", "FEBRASGO"},
     ["vacina", "gripe", "imunizacao", "vacinacao"]),
    (1, "ganho de peso recomendado durante a gestacao", {"SOGIMIG", "FEBRASGO"},
     ["ganho de peso", "peso", "nutricao"]),
    (1, "diagnostico de diabetes gestacional", {"SOGIMIG", "FEBRASGO"},
     ["diabetes gestacional", "diabetes", "glicemia"]),
    (1, "trabalho de parto em primigravida a termo", {"SOGIMIG"},
     ["trabalho de parto", "parto", "dilatacao"]),
    (1, "inicio do pre-natal de baixo risco", {"SOGIMIG", "FEBRASGO"},
     ["pre-natal", "prenatal", "assistencia ao pre-natal"]),
    (1, "cesarea eletiva indications", {"SOGIMIG", "Williams"},
     ["cesarea", "cesariana"]),
    (1, "acompanhamento pos-parto e consulta puerperal", {"SOGIMIG", "FEBRASGO"},
     ["puerperio", "pos-parto", "consulta puerperal"]),

    # ---- 02 Emergencias obstetricas ---------------------------------------
    (2, "conduta no descolamento prematuro de placenta", {"SOGIMIG"},
     ["descolamento", "placenta", "DPP"]),
    (2, "hemorragia na gestacao: como investigar", {"SOGIMIG", "FEBRASGO"},
     ["hemorragia", "sangramento"]),
    (2, "pre-eclampsia com sinais de gravidade", {"SOGIMIG", "FEBRASGO"},
     ["pre-eclampsia", "preeclampsia", "gravidade"]),
    (2, "sindrome de HELLP", {"SOGIMIG", "FEBRASGO"},
     ["HELLP", "hemolise", "fosphatoquinase"]),
    (2, "eclampsia: crise convulsiva na gestacao", {"SOGIMIG"},
     ["eclampsia", "convuls", "eclampsia"]),
    (2, "placenta previa", {"SOGIMIG", "FEBRASGO"},
     ["placenta previa", "previa", "placenta"]),
    (2, "rotura uterina", {"SOGIMIG"}, ["rotura uterina", "rotura", "utero"]),
    (2, "sepse materna", {"SOGIMIG", "FEBRASGO"}, ["sepse", "sepsis", "septicemia"]),
    (2, "sofrimento fetal: monitorizacao e conduta", {"SOGIMIG"},
     ["sofrimento fetal", "fetal", "cardiotocografia"]),
    (2, "abruptio placentae", {"SOGIMIG", "Williams"},
     ["descolamento", "abruptio", "placenta"]),

    # ---- 03 Medicina fetal e gestacao de alto risco ------------------------
    (3, "restricao de crescimento intrauterino", {"SOGIMIG", "FEBRASGO"},
     ["restricao", "crescimento intrauterino", "CIU", "RCIU"]),
    (3, "oligohidramnios e polihidramnios", {"SOGIMIG"},
     ["oligohidramnios", "polihidramnios", "liquido amn"]),
    (3, "gestacao gemelar de alto risco", {"SOGIMIG", "Williams"},
     ["gemelar", "gemin", "multipla"]),
    (3, "previa de vasa previa", {"SOGIMIG"}, ["vasa previa", "vasa", "previa"]),
    (3, "sindrome de transfusao fetomaterna", {"SOGIMIG", "Williams"},
     ["transfus", "feto-materna", "fetomaterna"]),
    (3, "malformacao fetal: diagnostico prenatal", {"SOGIMIG", "Williams"},
     ["malformac", "anomalia fetal", "malformacao"]),
    (3, "gestacao de alto risco: quais criterios", {"SOGIMIG", "FEBRASGO"},
     ["alto risco", "gestacao de alto risco", "risco"]),
    (3, "oligúria e polihidramnios na gestação", {"SOGIMIG"},
     ["polihidramnios", "liquido amn"]),
    (3, "monoarterial: significado e conduta", {"SOGIMIG", "Williams"},
     ["monoarterial", "arteria unica", "cordao"]),
    (3, "prenatal de alto risco com hipertensao cronica", {"SOGIMIG", "FEBRASGO"},
     ["hipertensao cronica", "cronica", "alto risco"]),
    (3, "mortalidade fetal intrauterina", {"SOGIMIG", "Williams"},
     ["morte fetal", "obito fetal", "intrauterin"]),
    (3, "saude fetal: rastreio no primeiro trimestre", {"SOGIMIG"},
     ["rastreio", "primeiro trimestre", "rastreamento"]),

    # ---- 04 Infertilidade e medicina reprodutiva --------------------------
    (4, "causas de infertilidade no casal", {"Williams", "FEBRASGO"},
     ["infertilidade", "infertil", "causas"]),
    (4, "investigacao da infertilidade feminina", {"Williams", "FEBRASGO"},
     ["investigacao", "infertilidade", "reserva ovariana"]),
    (4, "sindrome dos ovarios policisticos", {"Williams", "FEBRASGO"},
     ["policistic", "SOP", "ovarios policisticos"]),
    (4, "inseminacao artificial intrauterina: indicaciones", {"Williams", "FEBRASGO"},
     ["inseminacao", "IUI", "intrauterina"]),
    (4, "fertilizacao in vitro: etapas e prognostico", {"Williams", "FEBRASGO"},
     ["fertilizacao", "FIV", "ICSI", "in vitro"]),
    (4, "disfuncao ovulatoria: diagnostico", {"Williams", "FEBRASGO"},
     ["ovulacao", "anovulacao", "disfuncao ovulatoria"]),
    (4, "diagnostico de trompa de falopio obstruida", {"Williams"},
     ["trompa", "falopio", "histerossalpingografia"]),
    (4, "cavitacao uterina e hipoplasia", {"Williams"},
     ["cavidade uterina", "hipoplasia", "malformacao uterina"]),
    (4, "reserva ovariana diminished", {"Williams", "FEBRASGO"},
     ["reserva ovariana", "AMH", "diminuida"]),
    (4, "tratamento da infertilidade", {"Williams", "FEBRASGO"},
     ["tratamento", "infertilidade", "inducao de ovulacao"]),

    # ---- 05 Endocrinologia ginecologica ------------------------------------
    (5, "sindrome dos ovarios policisticos: diagnostico e tratamento", {"Williams", "FEBRASGO"},
     ["policistic", "SOP", "ovarios policisticos"]),
    (5, "hirsutismo: abordagem inicial", {"Williams", "FEBRASGO"},
     ["hirsutismo", "hirsutismo", "hiperandrogenismo"]),
    (5, "amenorreia: algoritmo de investigacao", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["amenorreia", "amenorrhea", "amenorreica"]),
    (5, "hiperprolactinemia", {"Williams", "FEBRASGO"},
     ["prolactina", "hiperprolactinemia", "galactorr"]),
    (5, "sindrome de Cushing na mulher", {"Williams", "FEBRASGO"},
     ["Cushing", "cortisol", "hipercortisolismo"]),
    (5, "congenital adrenal hyperplasia", {"Williams", "FEBRASGO"},
     ["adrenal", "CAH", "hiperplasia adrenal"]),
    (5, "disfuncao da tireoide e ciclo menstrual", {"Williams", "FEBRASGO"},
     ["tireoide", "tiroide", "hipotireoidismo"]),
    (5, "sindrome de resistencia a insulina", {"Williams", "FEBRASGO"},
     ["insulina", "resistencia", "sindrome metabolico"]),
    (5, "obesidade e disturbing menstrual", {"Williams", "FEBRASGO"},
     ["obesidade", "obesidade", "ciclo menstrual"]),
    (5, "hirsutismo e sindrome dos ovarios policisticos", {"Williams", "FEBRASGO"},
     ["hirsutismo", "policistic", "SOP"]),
    (5, "diagnostico de diabetes em mulher com SOP", {"Williams", "FEBRASGO"},
     ["diabetes", "glicemia", "SOP"]),
    (5, "glicemia e resistencia a insulina no sop", {"Williams", "FEBRASGO"},
     ["glicemia", "diabetes", "insulina"]),

    # ---- 06 Menopausa e terapia hormonal ------------------------------------
    (6, "diagnostico da menopausa", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["menopausa", "menopausa", "perimenopausa"]),
    (6, "terapia hormonal da menopausa: quem pode usar", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["terapia hormonal", "hormonioterapia", "TH"]),
    (6, "contraindicacao da terapia hormonal", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["contraindic", "contraindicacoes", "risco"]),
    (6, "osteoporose pos-menopausa", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["osteoporose", "densidade ossea", " BMD"]),
    (6, "sofocos e sintomas vasomotores", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["sofoco", "sudorese", "sintomas vasomotores", "calor"]),
    (6, "disfuncao sexual apos a menopausa", {"Williams", "FEBRASGO"},
     ["disfuncao sexual", "libido", "sexualidade"]),
    (6, "doença cardiovascular apos a menopausa", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["cardiovascular", "coracao", "cardio"]),
    (6, "terapia hormonal e risco de cancer de mama", {"Williams", "FEBRASGO"},
     ["cancer de mama", "mama", "malignidade"]),

    # ---- 07 Contracepcao e planejamento familiar ----------------------------
    (7, "tabagismo e uso de metode contraceptivo hormonal", {"SOGIMIG", "FEBRASGO"},
     ["tabagismo", "tabaco", "fumante", "tabagista"]),
    (7, "obesidade e risco de tromboembolismo com metodo hormonal",
     {"SOGIMIG", "FEBRASGO", "Williams"},
     ["obesidade", "tromboembol", "TEV"]),
    (7, "DIU de cobre: indicacoes e contraindicacoes", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["DIU", "cobre", "dispositivo intrauterino"]),
    (7, "DIU de levonorgestrel", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["levonorgestrel", "DIU", "intrauterino"]),
    (7, "contracepcao de emergencia", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["emergencia", "emergencial", "levonorgestrel"]),
    (7, "anticoncepcional oral combinado: contraindicacoes", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["contraceptivo oral", "COC", "combinado", "anticoncepcional"]),
    (7, "adesao ao metodo contraceptivo", {"SOGIMIG", "FEBRASGO"},
     ["adesao", "adesão", "abandono"]),
    (7, "esterilizacao surgically: requisitos legais", {"SOGIMIG", "FEBRASGO"},
     ["esterilizacao", "esterilização", "laqueadura"]),
    (7, "consentimento informado no planejamento familiar", {"SOGIMIG", "FEBRASGO"},
     ["consentimento", "manifestacao de vontade", "informacao"]),
    (7, "metodos anticoncepcionais disponiveis e aceitabilidade",
     {"SOGIMIG", "FEBRASGO"},
     ["metodos", "metodo", "anticoncepcional"]),

    # ---- 08 Uroginecologia e piso pelvico -----------------------------------
    (8, "incontinencia urinaria de esforco", {"Williams", "FEBRASGO"},
     ["incontinencia", "esforco", "urinaria"]),
    (8, "incontinencia urinaria na gestacao", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["incontinencia", "gestacao", "urinaria"]),
    (8, "prolapso uterino: graus e tratamento", {"Williams", "FEBRASGO"},
     ["prolapso", "prolapso uterino", "queda uterina"]),
    (8, "reeducacao do perineo", {"Williams", "FEBRASGO"},
     ["perineo", "períneo", "reeducacao", "fisioterapia"]),
    (8, "disfuncao sexual dolorosa", {"Williams", "FEBRASGO"},
     ["dor", "sexual", "vulvodinia", "dispareunia"]),
    (8, "incontinencia apos o parto", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["incontinencia", "pos-parto", "perineo"]),
    (8, "sindrome da bexiga hiperativa", {"Williams", "FEBRASGO"},
     ["hiperativa", "bexiga", "urgencia miccional"]),

    # ---- 09 Oncologia ginecolica -------------------------------------------
    (9, "cancer de colo uterino: rastreio e tratamento", {"Williams", "FEBRASGO"},
     ["colo uterino", "cervical", "cervicite", "citologia"]),
    (9, "cancer de ovario: diagnostico", {"Williams", "FEBRASGO"},
     ["ovario", "ovarico", "tumor de ovario"]),
    (9, "cancer de endometrio: fatores de risco", {"Williams", "FEBRASGO"},
     ["endometrio", "endometrial", "endometriose", "hiperplasia"]),
    (9, "estadiamento do cancer gynecologico", {"Williams"},
     ["estadiamento", "FIGO", "estadio"]),
    (9, "rastreio de cancer de mama", {"Williams", "FEBRASGO"},
     ["mama", "mamografia", "rastreio"]),
    (9, "lesoes pré-malignas do colo", {"Williams", "FEBRASGO"},
     ["pre-maligna", "displasia", "HSIL", "lesao intraepitelial"]),
    (9, "quimioterapia no cancer gynecologico", {"Williams"},
     ["quimioterapia", "quimio", "citostatico"]),
    (9, "tumor de mama: diagnostico por imagem", {"Williams"},
     ["mama", "nodulo mamario", "mamografia", "ultrassonografia"]),

    # ---- 10 Mastologia ------------------------------------------------------
    (10, "nodulo mamario: abordagem", {"Williams", "FEBRASGO"},
     ["nodulo", "mamario", "mama"]),
    (10, "carcinoma de mama: estadiamento e tratamento", {"Williams", "FEBRASGO"},
     ["carcinoma de mama", "mama", "malignidade"]),
    (10, "mastalgia e discharge mamario", {"Williams", "FEBRASGO"},
     ["mastalgia", "discharge", "mamilo", "mastodinia"]),
    (10, "rastreio mamografico populacional", {"Williams", "FEBRASGO"},
     ["mamografia", "rastreio", "rastreamento"]),

    # ---- 11 Ginecologia pediatrica e do adolescente -------------------------
    (11, "menarca precoce e tardia", {"Williams", "FEBRASGO"},
     ["menarca", "menarca", "puberdade"]),
    (11, "sangramento vaginal na adolescente", {"Williams", "FEBRASGO"},
     ["adolescente", "sangramento", "pubert"]),
    (11, "anomalia de Muller e agenesia uterina", {"Williams"},
     ["Muller", "agenesia uterina", "anomalia uterina"]),
    (11, "violencia sexual em adolescente", {"Williams", "FEBRASGO"},
     ["violencia", "estupro", "abus"]),
    (11, "puberdade precoce central", {"Williams", "FEBRASGO"},
     ["puberdade precoce", "precoce", "gonadotropina"]),
    (11, "cistos ovarianos neonatais", {"Williams"},
     ["cisto", "ovario", "neonat", "pediatr"]),

    # ---- 12 Colposcopia e lesoes do tracto genital inferior -----------------
    (12, "citologia cervical alterada: conduta", {"Williams", "FEBRASGO"},
     ["citologia", "Pap", "Papanicolaou", "cervical"]),
    (12, "HPV: deteccao e acompanhamento", {"Williams", "FEBRASGO"},
     ["HPV", "papilomavirus", "papiloma"]),
    (12, "condiloma acuminado: tratamento", {"Williams", "FEBRASGO"},
     ["condiloma", "condiloma acuminado", "verruga"]),
    (12, "cervicite e vaginite: diagnostico", {"Williams", "FEBRASGO"},
     ["cervicite", "vaginite", "vaginose"]),
    (12, "lesao intraepitelial cervical HSIL", {"Williams", "FEBRASGO"},
     ["HSIL", "intraepitelial", "displasia"]),
    (12, "herpes genital", {"Williams", "FEBRASGO"},
     ["herpes", "herpes genital", "viral"]),

    # ---- 13 Cirurgia ginecolica --------------------------------------------
    (13, "histeroscopia: indicacoes", {"Williams", "FEBRASGO"},
     ["histeroscopia", "histeroscop", "endometrio"]),
    (13, "laparoscopia ginecológica", {"Williams", "FEBRASGO"},
     ["laparoscopia", "laparoscop", "endoscop"]),
    (13, "miomectomia: vias de acesso", {"Williams", "FEBRASGO"},
     ["miomectomia", "mioma", "leiomioma"]),
    (13, "histerectomia: preparo e riscos", {"Williams", "FEBRASGO"},
     ["histerectomia", "histerectomia", "utero"]),
    (13, "cirurgia minimamente invasivaAdvantages", {"Williams", "FEBRASGO"},
     ["cirurgia", "laparoscop", "minimamente invasiva"]),

    # ---- 14 Endometriose ---------------------------------------------------
    (14, "diagnostico da endometriose", {"Williams", "FEBRASGO"},
     ["endometriose", "endometriose", "endometrio"]),
    (14, "tratamento da endometriose", {"Williams", "FEBRASGO"},
     ["endometriose", "tratamento", "terapia"]),
    (14, "endometriose e infertilidade", {"Williams", "FEBRASGO"},
     ["endometriose", "infertilidade", "infertil"]),
    (14, "dor pelvica cronica por endometriose", {"Williams", "FEBRASGO"},
     ["dor pelvica", "endometriose", "endometriosis"]),
    (14, "endometrioma: conduta", {"Williams", "FEBRASGO"},
     ["endometrioma", "cisto", "endometriose"]),
    (14, "endometriose intestinal e urinária", {"Williams", "FEBRASGO"},
     ["endometriose", "intestinal", "urinari"]),

    # ---- 15 Adenomiose -----------------------------------------------------
    (15, "adenomiose: diagnostico e tratamento", {"Williams", "FEBRASGO"},
     ["adenomiose", "adenomiose", "adenomio"]),
    (15, "adenomiose: diferenca do leiomioma", {"Williams", "FEBRASGO"},
     ["adenomiose", "leiomioma", "mioma"]),
    (15, "adenomiose e hemorragia uterina", {"Williams", "FEBRASGO"},
     ["adenomiose", "hemorragia", "menorragia"]),

    # ---- 16 Leiomiomas -----------------------------------------------------
    (16, "leiomioma uterino: diagnostico", {"Williams", "FEBRASGO"},
     ["leiomioma", "mioma", "fibroma"]),
    (16, "tratamento de mioma sintomatico", {"Williams", "FEBRASGO"},
     ["mioma", "leiomioma", "tratamento"]),
    (16, "mioma e infertilidade", {"Williams", "FEBRASGO"},
     ["mioma", "infertilidade", "leiomioma"]),
    (16, "degeneracao do leiomioma", {"Williams", "FEBRASGO"},
     ["degener", "leiomioma", "mioma"]),
    (16, "espiralizacao e embolizacao de mioma", {"Williams", "FEBRASGO"},
     ["embolizacao", "espiralizacao", "mioma"]),

    # ---- 17 Disturbios menstruais ------------------------------------------
    (17, "menorragia: abordagem", {"Williams", "FEBRASGO"},
     ["menorragia", "menstruacao abundante", "fluxo"]),
    (17, "disfuncao menstrual e anovulacao", {"Williams", "FEBRASGO"},
     ["anovulacao", "disfuncao menstrual", "ciclo menstrual"]),
    (17, "dismenorreia primaria e secundaria", {"Williams", "FEBRASGO"},
     ["dismenorreia", "dismenorrea", "dor menstrual"]),
    (17, "sindrome premenstrual e transtorno disfórico", {"Williams", "FEBRASGO"},
     ["premenstrual", "TPM", "dismorico", "fase lutea"]),
    (17, "amenorreia hipogonadotropa", {"Williams", "FEBRASGO"},
     ["amenorreia", "hipogonadotropa", "gonadotropina"]),

    # ---- 18 Dor pelvica cronica --------------------------------------------
    (18, "dor pelvica cronica: algoritmo", {"Williams", "FEBRASGO"},
     ["dor pelvica", "dor pélvica", "cronica"]),
    (18, "adesoes pélvicas", {"Williams", "FEBRASGO"},
     ["adesao", "adesões", "aderencias", "endometriose"]),
    (18, "síndrome da dor pélvica crônica", {"Williams", "FEBRASGO"},
     ["dor pelvica", "ciclica", "cronica"]),

    # ---- 19 Infeccoes, PID e DST --------------------------------------------
    (19, "doenca inflamatoria pélvica", {"Williams", "FEBRASGO"},
     ["inflamatoria pelvica", "PID", "DIP", "salpingite"]),
    (19, "cervicite por clamidia e gonococo", {"Williams", "FEBRASGO"},
     ["clamidia", "gonococo", "cervicite", "gonor"]),
    (19, "candidíase vaginal: diagnóstico e tratamento", {"Williams", "FEBRASGO"},
     ["candid", "candida", "moniliaz"]),
    (19, "vaginose bacteriana", {"Williams", "FEBRASGO"},
     ["vaginose", "bacteriana", "gardnerella"]),
    (19, "sequela de PID: dor pelvica cronica e infertilidade", {"Williams", "FEBRASGO"},
     ["PID", "sequela", "dor pelvica", "infertilidade"]),
    (19, "doenca inflamatoria pelvica cronica", {"Williams", "FEBRASGO"},
     ["PID", "DIP"]),

    # ---- 20 Aborto espontaneo e perda gestacional recorrente ---------------
    (20, "aborto espontaneo: causas", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["aborto espontaneo", "aborto", "perda gestacional"]),
    (20, "aborto recorrente: investigacao", {"Williams", "FEBRASGO"},
     ["aborto recorrente", "recorrente", "perda gestacional"]),
    (20, "cariotipo e anomalia cromossomica no aborto", {"Williams"},
     ["cariotipo", "cromossom", "aneuploidia"]),
    (20, "aborto espontaneo: conduta", {"Williams", "SOGIMIG"},
     ["aborto", "conduta", "expulsao"]),
    (20, "sindrome de Asherman", {"Williams", "FEBRASGO"},
     ["Asherman", "aderencias uterinas", "sinquea"]),

    # ---- 21 Gestacao ectopica ----------------------------------------------
    (21, "gestacao ectopica: diagnóstico", {"SOGIMIG", "Williams", "FEBRASGO"},
     ["ectopica", "ectopico", "ectopic", "ectópica"]),
    (21, "dor em fossa iliaca: differential", {"SOGIMIG", "Williams"},
     ["fossa iliaca", "ectopica", "dor"]),
    (21, "beta-hCG e ultrassonografia na ectopica", {"SOGIMIG", "Williams"},
     ["hCG", "beta-hCG", "ultrassonografia"]),
    (21, "tratamento da gestacao ectopica: metionato e cirurgia", {"SOGIMIG", "Williams"},
     ["metionato", "salpingectomia", "cirurgia"]),
    (21, "ectopica persistente", {"SOGIMIG", "Williams"},
     ["ectopica", "persistente", "hCG"]),
    (21, "ruptura de ectopica: emergencia", {"SOGIMIG", "Williams"},
     ["ruptura", "ectopica", "hemorragia"]),

    # ---- 22 Hemorragia uterina anomala -------------------------------------
    (22, "hemorragia uterina anomala:ifferential", {"Williams", "FEBRASGO"},
     ["hemorragia uterina", "menorragia", "sangramento uterino"]),
    (22, "sangramento na gestacao: classificação", {"SOGIMIG", "FEBRASGO"},
     ["sangramento", "hemorragia", "gestacao"]),
    (22, "mioma e hemorragia uterina", {"Williams", "FEBRASGO"},
     ["mioma", "hemorragia", "menorragia"]),
    (22, "histeroscopia no sangramento uterino", {"Williams", "FEBRASGO"},
     ["histeroscopia", "sangramento", "hemorragia"]),

    # ---- 23 Dor aguda ginecológica e abdomen agudo -------------------------
    (23, "abdomen agudo na mulher: differential", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["abdomen agudo", "abdome agudo", "dor abdominal"]),
    (23, "torsao anexial", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["torsao", "torsão", "anexial", "ovario"]),
    (23, "torcao anexial: ultrassonografia com doppler", {"Williams", "FEBRASGO"},
     ["torsao", "doppler", "ultrassonografia"]),
    (23, "apendicite na mulher: differential", {"Williams", "SOGIMIG"},
     ["apendicite", "apendicite", "diferencial"]),

    # ---- 24 Clímaterio e saude da mulher idosa -----------------------------
    (24, "saude cardiovascular da mulher idosa", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["cardiovascular", "coracao", "cardio", "coracao"]),
    (24, "osteoporose e fratura: prevencao", {"Williams", "FEBRASGO", "SOGIMIG"},
     ["osteoporose", "fratura", "densidade ossea"]),
    (24, "incontinencia geriatrica", {"Williams", "FEBRASGO"},
     ["incontinencia", "geriatrica", "idosa"]),
    (24, "envelhecimento e saúde da mulher", {"SOGIMIG", "FEBRASGO", "Williams"},
     ["idosa", "envelhecimento", "climaterio", "climaterio"]),
]
